### ISSUE TITLE
Conditional and Marginal R2 for WeMix

### ISSUE THREAD

**Issue by joaomaroco** [American-Institutes-for-Research/EdSurvey#72] opened 2024-04-03 07:31 UTC
I would like to calculate the Conditional R2 and marginal R2 for WeMix objects. Is there an easy way to recover the variance associated with fixed effects and the variance associated with the different random effects?
Thanks!

**Comment by pdbailey0** [comment] 2024-04-03 12:47
@joaomaroco sorry to again redirect you, but are you directly calling WeMix? if so, please post on the [WeMix GitHub page](https://github.com/American-Institutes-for-Research/WeMix/issues).

**Comment by pdbailey0** [comment] 2024-04-03 14:01
duplicate of https://github.com/American-Institutes-for-Research/WeMix/issues/16

**Closed by pdbailey0** 2024-04-03 14:01 UTC
